### PR TITLE
Separate status setting and handle failures

### PR DESCRIPTION
**Pull request by ghost**
This move status handling into its own function and adds handling when status setting fails

@childsb @jsafrane @rootfs @saad-ali @thockin

### CODE REVIEW

**Comment by pmorie** [comment]
This LGTM and seems completely non-controversial

**Comment by thockin** [comment]
LGTM - nice

**Comment by thockin** [comment]
let's be wary to keep the structure of the major if-elseif-else tree as we add code

**Comment by ghost** [comment]
> let's be wary to keep the structure of the major if-elseif-else tree as we add code

Sounds good

**Pull request merged**
